SELECT
    E.EMPLOYEE_ID,
    E.FIRST_NAME,
    E.LAST_NAME,
    E.SALARY,
    E.DEPARTMENT_ID,
    D.DEPARTMENT_NAME,
    CASE
        WHEN E.SALARY > 10000 THEN 'HIGH'
        ELSE 'LOW'
    END SALARY_LEVEL,
    COALESCE(E.COMMISSION_PCT, 0) COMM,
    SYSDATE AS RUNDATE
FROM HR.EMPLOYEES E
LEFT JOIN HR.DEPARTMENTS D
    ON E.DEPARTMENT_ID = D.DEPARTMENT_ID
WHERE
    1 = 1
    AND E.DEPARTMENT_ID IN (10, 20, 30, 40)
    AND SALARY > 5000
    AND (
        E.JOB_ID = 'IT_PROG'
        OR JOB_ID = 'SA_MAN'
    )
    AND E.HIRE_DATE < TO_DATE('2018-01-01', 'YYYY-MM-DD')
ORDER BY DEPARTMENT_ID ASC, SALARY DESC;


-- segundo query deliberadamente mal escrito
SELECT *
FROM HR.EMPLOYEES EMP, HR.JOBS J
WHERE
    EMP.JOB_ID = J.JOB_ID
    AND EMP.MANAGER_ID = J.JOB_ID
    AND EMP.SALARY > (SELECT AVG(SALARY) FROM HR.EMPLOYEES)
ORDER BY EMP.FIRST_NAME, EMP.LAST_NAME;


WITH DEPT_SAL AS (
    SELECT
        DEPARTMENT_ID,
        SUM(SALARY) TOTAL_SAL,
        AVG(SALARY) AVG_SAL
    FROM HR.EMPLOYEES
    GROUP BY DEPARTMENT_ID
)

SELECT *
FROM DEPT_SAL DS
WHERE AVG_SAL > (SELECT AVG(SALARY) FROM HR.EMPLOYEES)
ORDER BY 1;


SELECT
    EMP.EMPLOYEE_ID,
    EMP.FIRST_NAME,
    EMP.LAST_NAME,
    (
        SELECT COUNT(*) FROM HR.EMPLOYEES E2
        WHERE E2.MANAGER_ID = EMP.EMPLOYEE_ID
    ) AS TEAMSIZE
FROM HR.EMPLOYEES EMP
WHERE
    EMP.EMPLOYEE_ID IN
    (
        SELECT EMPLOYEE_ID FROM HR.EMPLOYEES
        WHERE SALARY > 9000
    )
    AND EMP.DEPARTMENT_ID NOT IN (
        SELECT DEPARTMENT_ID FROM HR.DEPARTMENTS
        WHERE LOCATION_ID = 1700
    );


SELECT
    DEPARTMENT_ID,
    SUM(CASE WHEN SALARY > 10000 THEN 1 ELSE 0 END) HIGH_PAID,
    SUM(CASE WHEN SALARY <= 10000 THEN 1 ELSE 0 END) LOW_PAID
FROM HR.EMPLOYEES
GROUP BY DEPARTMENT_ID
HAVING SUM(SALARY) > 50000
ORDER BY DEPARTMENT_ID;
